### PR TITLE
Enable RHEL images

### PR DESCRIPTION
**Pull request by riuvshin**
Enable RHEL images

@fche I was able to find in that repo only these images used:
```
pcp-bayesian-central-logger
pcp-bayesian-webapi-guard
pcp-central-logger
pcp-central-webapi
pcp-webapi-guard
pcp-postgresql-monitor
oso-central-logger
oso-central-webapi-guard
```

but these are not used in that repo, can you point me please where these images are used to update the links for them or they just obsolete?
```
mm-zabbix-relay
oso-pcp-prometheus
oso-webapi-guard
pcp-node-collector
```

@fche another note that  I was unable to find where `bayesian-monitor.yml` is used but found this: https://github.com/openshiftio/saas-analytics/pull/183, so does this a right PR for `bayesian-monitor.yml` from that repo? If so it have to be updated after this PR will be merged
cc @syamgk @rawlingsj

### CODE REVIEW

**Comment by fche** [comment]
> can you point me please where these images are used to update the links for them or they just obsolete?

> mm-zabbix-relay

Was / is? used in a pcp instrumentation experiment for chat.openshift.io.

> oso-pcp-prometheus
> oso-webapi-guard

Obsoleted.

> pcp-node-collector

Used by the osd node monitoring daemonset in a separate SD-team-owned dc yml.

**Comment by fche** [comment]
(If you'd like this merged, please drop the WIP from the subject line)

**Comment by riuvshin** [comment]
@fche can be merged now

**Comment by syamgk** [comment]
`mm-zabbix-relay`
we are still using it for monitoring chat.openshift.io
https://github.com/rhdt/chat/blob/master/openshift/mattermost.app.yaml#L67

**Comment by riuvshin** [comment]
thanks @syamgk  now it is more clear.

**Pull request merged**
